server:
  port: 8081

spring:
  application:
    name: crawling-service
  profiles:
    active: local
  config:
    import:
      - application-secret.yml
      - configserver:localhost:8888
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
