server:
  port: 9001

spring:
  application:
    name: api-gateway
  config:
    import: application-secret.yml
  cloud:
    gateway:
      routes:
        - id: member-service-auth
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/auth/login, /api/auth/signup
          filters: []

        - id: member-service-secure
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/auth/**
          filters: JwtAuthenticationFilter

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

jwt:
  expired:
    access-token: 300000 # 5 minute
    refresh-token: 31536000000 # 1 year
