server:
  port: 8083

spring:
  application:
    name: member-service
  config:
    import:
      - application-db.yml
      - application-secret.yml
  data:
    redis:
      host: localhost
      port: 6379

eureka:
#  instance:
#    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
jwt:
  expired:
    access-token: 300000 # 5 minute
    refresh-token: 31536000000 # 1 year

management:
  endpoints:
    web:
      exposure:
        include: "*"


