server:
  port: 8083

spring:
  application:
    name: member-service
  profiles:
    active: local
  config:
    import:
      - application-secret.yml
      - configserver:http://localhost:8888
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
