spring:
  application:
    name: config-server
  profiles:
    active: local
  config:
    import: application-secret.yml
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Switch-Switch/service-config.git
          search-paths: config-files/**
          default-label: main
          ignore-local-ssh-settings: true
server:
  port: 8888

---
spring:
  config:
    activate:
      on-profile: local
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
